# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe7914a75698e1706822a0f1624da7340212971118bcabf4f02a90db8c734a9246594ceade1f3236bcd2d8c7e86808c7daab56cd7f08e1d4877140140f6ddd9

test:
  secret_key_base: 8cbfbb3b67c8ccd5841771e6260c1249edd59e1181654afc36be62f9b0118e8477db52218ac96481cecad356bcf5ebedbc75c5f3b264e8b49dad773f53d54192

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
